### PR TITLE
chore: include unocha modules in periodic updates

### PR DESCRIPTION
**Pull request by lazysoundsystem**
Refs: OPS-10151

### CODE REVIEW

**Review by cafuego — APPROVED** [review]
Fair enough.

**Comment by lazysoundsystem** [comment]
@cafuego Does this need a nudge to become activated?

If so, I'd like to add 'druah/*' to the list too.

**Comment by cafuego** [comment]
No, this should be automagically getting run by all projects that don't specify their own patch_packages parameter. You could add druah, but I'd suggest drush instead.

**Comment by lazysoundsystem** [comment]
Ah, that's a new one - my go to typo is `dursh`

Made a ticket to remove `patch_package` config from sites unless we have a reason to include it: https://humanitarian.atlassian.net/browse/OPS-10217

**Pull request merged**
